name: Publish Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      directory:
        description: 'Build docs'
        default: 'build it now'
        required: false


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: "3.12"
    - uses: pre-commit/action@v3.0.1
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.8.2
      - name: Install Packages
        run: poetry install --with docs,tutorial
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Build Docs
        run: poetry run mkdocs build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: site
          clean-exclude: pr-preview/
          force: false
