name: Publish Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      directory:
        description: 'Build docs'
        default: 'build it now'
        required: false


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.12"
    - uses: pre-commit/action@v3.0.1
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Build Docs
        run: uv run mkdocs build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: site
          clean-exclude: pr-preview/
          force: false
